### PR TITLE
#favorite_opponent

### PR DESCRIPTION
**Pull request by gabichuelas**
@rrabinovitch @sciencefixion @evilaspaas1 
All tests pass :)

### CODE REVIEW

**Comment by gabichuelas** [comment]
Nevermind. All tests pass... but the spec harness doesn't on this method. Guess it's time to figure out why not.

**Comment by gabichuelas** [comment]
@rrabinovitch @sciencefixion @evilaspaas1 
This PR has a lot more on it than it should, but, the important part is that I added 3 new methods to `Game` class: `winner`, `loser`, and `result` so that we don't have to cross reference with game_teams anymore for a lot of methods. This will help with refactoring. 

I skipped tests (for my Team methods) that don't work for this PR, so it's safe to merge so y'all can use the new code in Game.

**Comment by gabichuelas** [comment]
@rrabinovitch @evilaspaas1 @sciencefixion 
All tests pass. `favorite_opponent` WORKS.

**Review by araspaas — APPROVED** [review]
cool glad you were able to figure out what was going on for favorite opponent

**Comment by sciencefixion** [comment]
I'm going to go ahead and merge. This is great stuff!

**Pull request merged**
